import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { FilePondFile, FilePondInitialFile } from "filepond";

// Import React FilePond
import { FilePond, registerPlugin } from 'react-filepond';

// Import FilePond styles
// Import the Image EXIF Orientation and Image Preview plugins
// Note: These need to be installed separately
// `npm i filepond-plugin-image-preview filepond-plugin-image-exif-orientation --save`
import FilePondPluginImageExifOrientation from 'filepond-plugin-image-exif-orientation';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import { useEffect, useState } from "react";
import PurchaseButton from "../components/PurchaseButton";


// Register the plugins
registerPlugin(FilePondPluginImageExifOrientation, FilePondPluginImagePreview);

type Style = {
  name: string,
  preview: string,
}

const Home: NextPage = () => {

  const styles = [
    { name: "anime", preview: "/anime.jpeg" },
    { name: "cartoon", preview: "/anime.jpeg" },
    { name: "photo", preview: "/anime.jpeg" },
    { name: "portrait", preview: "/anime.jpeg" },
    { name: "sketch", preview: "/anime.jpeg" },
    { name: "watercolor", preview: "/anime.jpeg" },
  ] as Style[]

  const [files, setFiles] = useState<FilePondFile[]>();
  const [selectedStyle, setSelectedStyle] = useState<Style>(styles[0] as Style)

  useEffect(() => {
    files?.map((file) => {
      console.log(file.file);
    });
    console.log(files?.length)
  }, [files]);

  return (
    <>
      <Head>
        <title>AI Portraits</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col space-y-8 justify-center items-center">
        <div className="w-1/3 mx-auto overflow-y-scroll max-h-96">
          <FilePond
            files={files as any}
            onupdatefiles={setFiles}
            allowMultiple={true}
            maxFiles={20}
            server="/api/upload"
            name="files"
            labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
          />
        </div>
        <div className="w-2/3 border-violet-600 border-4 p-4 rounded-xl mx-auto flex items-center space-x-4 overflow-x-auto">
          {styles.map((style) => (
            <div key={style.name}>
              <div className={`${selectedStyle.name === style.name ? "border-2 border-violet-500" : null} cursor-pointer h-96 w-72 flex-none rounded-md bg-slate-200`}
                onClick={() => setSelectedStyle(style)}>
                <p className='text-center text-xl p-2 '>{style.name}</p>
                <img className='h-72' src={style.preview} alt={style.name} />
              </div>
            </div>
          ))}
        </div>
        {/* <a href="https://storyset.com/technology">Technology illustrations by Storyset</a> */}
        <PurchaseButton />
      </main>
    </>
  );
};

export default Home;
